version: '3.5'

services:

  cleverdev-old-client:
    image: cleverdev-old-client:latest
    container_name: cleverdev-old-client
    build: cleverdev-old-client
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:mem:mydb
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: password

  new-client-service:
    image: new-client-service:latest
    container_name: new-client-service
    depends_on:
      database:
        condition: service_started
    build: cleverdev-test-task
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/client_db
      SPRING_DATASOURCE_USERNAME: client
      SPRING_DATASOURCE_PASSWORD: password

  database:
    container_name: database
    image: postgres
    environment:
      POSTGRES_USER: client
      POSTGRES_PASSWORD: password
      POSTGRES_DB: client_db
    ports:
      - "5432:5432"
    restart: unless-stopped

  h2:
    image: buildo/h2database
    container_name: h2
    ports:
      - '8081:8082'
